# Generated by Django 5.1.2 on 2024-11-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot.area')),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('tiempo_estimado', models.CharField(max_length=50)),
                ('ceco', models.CharField(max_length=100)),
                ('jefe_proyecto', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('otros', models.CharField(blank=True, max_length=255)),
                ('observacion', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot.area')),
                ('materiales', models.ManyToManyField(to='ot.material')),
                ('tareas', models.ManyToManyField(to='ot.tarea')),
                ('tipo_paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot.tipoparadero')),
            ],
        ),
    ]
